
[pytest]
testpaths = tests
addopts =
    -v
    -s
    --browser chromium
    --headed
    --screenshot only-on-failure
    --video retain-on-failure
    --alluredir allure-results
    --clean-alluredir

#loger
log_cli = true
log_cli_level = INFO
log_cli_format = %(asctime)s | %(levelname)s | %(message)s

markers =
    api: mark api test
    ui: mark web ui test
    smoke: mark smoke test
    regression: mark regression test